const testCase = [
  {
    id: 1,
    images: ['https://source.unsplash.com/cdRUE5bHCGc/1600x900', 'https://source.unsplash.com/hrlvr2ZlUNk/1600x900'],
    theme: '가족',
    title: '뉴욕 한끼',
    score: 4,
    headcount: 4,
    restaurant: {
      id: 1,
      name: 'CakeHouse',
      location: '대전광역시 유성구 덕명동 수서로 1',
    },
    writer: {
      id: 1,
      username: 'userA',
      profile_img: 'https://source.unsplash.com/IhuHLIxS_Tk/1600x900',
    },
    bookmarked: false,
    viewd_num: 10,
  },
  {
    id: 2,
    images: ['https://source.unsplash.com/hrlvr2ZlUNk/1600x900', 'https://source.unsplash.com/cdRUE5bHCGc/1600x900'],
    theme: '가족',
    title: '프랑스 한끼',
    score: 5,
    headcount: 4,
    restaurant: {
      id: 2,
      name: 'ZIP BAP',
      location: '대전광역시 유성구 덕명동 수서로 2',
    },
    writer: {
      id: 2,
      username: 'userB',
      profile_img: 'https://source.unsplash.com/lkMJcGDZLVs/1600x900',
    },
    bookmarked: true,
    viewd_num: 12,
  },
  {
    id: 1,
    images: ['https://source.unsplash.com/cdRUE5bHCGc/1600x900', 'https://source.unsplash.com/hrlvr2ZlUNk/1600x900'],
    theme: '가족',
    title: '뉴욕 한끼',
    score: 4,
    headcount: 4,
    restaurant: {
      id: 1,
      name: 'CakeHouse',
      location: '대전광역시 유성구 덕명동 수서로 1',
    },
    writer: {
      id: 1,
      username: 'userA',
      profile_img: 'https://source.unsplash.com/IhuHLIxS_Tk/1600x900',
    },
    bookmarked: false,
    viewd_num: 10,
  },
  {
    id: 2,
    images: ['https://source.unsplash.com/hrlvr2ZlUNk/1600x900', 'https://source.unsplash.com/cdRUE5bHCGc/1600x900'],
    theme: '가족',
    title: '프랑스 한끼',
    score: 5,
    headcount: 4,
    restaurant: {
      id: 2,
      name: 'ZIP BAP',
      location: '대전광역시 유성구 덕명동 수서로 2',
    },
    writer: {
      id: 2,
      username: 'userB',
      profile_img: 'https://source.unsplash.com/lkMJcGDZLVs/1600x900',
    },
    bookmarked: true,
    viewd_num: 12,
  },
  {
    id: 1,
    images: ['https://source.unsplash.com/cdRUE5bHCGc/1600x900', 'https://source.unsplash.com/hrlvr2ZlUNk/1600x900'],
    theme: '가족',
    title: '뉴욕 한끼',
    score: 4,
    headcount: 4,
    restaurant: {
      id: 1,
      name: 'CakeHouse',
      location: '대전광역시 유성구 덕명동 수서로 1',
    },
    writer: {
      id: 1,
      username: 'userA',
      profile_img: 'https://source.unsplash.com/IhuHLIxS_Tk/1600x900',
    },
    bookmarked: false,
    viewd_num: 10,
  },
  {
    id: 2,
    images: ['https://source.unsplash.com/hrlvr2ZlUNk/1600x900', 'https://source.unsplash.com/cdRUE5bHCGc/1600x900'],
    theme: '가족',
    title: '프랑스 한끼',
    score: 5,
    headcount: 4,
    restaurant: {
      id: 2,
      name: 'ZIP BAP',
      location: '대전광역시 유성구 덕명동 수서로 2',
    },
    writer: {
      id: 2,
      username: 'userB',
      profile_img: 'https://source.unsplash.com/lkMJcGDZLVs/1600x900',
    },
    bookmarked: true,
    viewd_num: 12,
  },
  {
    id: 1,
    images: ['https://source.unsplash.com/cdRUE5bHCGc/1600x900', 'https://source.unsplash.com/hrlvr2ZlUNk/1600x900'],
    theme: '가족',
    title: '뉴욕 한끼',
    score: 4,
    headcount: 4,
    restaurant: {
      id: 1,
      name: 'CakeHouse',
      location: '대전광역시 유성구 덕명동 수서로 1',
    },
    writer: {
      id: 1,
      username: 'userA',
      profile_img: 'https://source.unsplash.com/IhuHLIxS_Tk/1600x900',
    },
    bookmarked: false,
    viewd_num: 10,
  },
  {
    id: 2,
    images: ['https://source.unsplash.com/hrlvr2ZlUNk/1600x900', 'https://source.unsplash.com/cdRUE5bHCGc/1600x900'],
    theme: '가족',
    title: '프랑스 한끼',
    score: 5,
    headcount: 4,
    restaurant: {
      id: 2,
      name: 'ZIP BAP',
      location: '대전광역시 유성구 덕명동 수서로 2',
    },
    writer: {
      id: 2,
      username: 'userB',
      profile_img: 'https://source.unsplash.com/lkMJcGDZLVs/1600x900',
    },
    bookmarked: true,
    viewd_num: 12,
  },
  {
    id: 1,
    images: ['https://source.unsplash.com/cdRUE5bHCGc/1600x900', 'https://source.unsplash.com/hrlvr2ZlUNk/1600x900'],
    theme: '가족',
    title: '뉴욕 한끼',
    score: 4,
    headcount: 4,
    restaurant: {
      id: 1,
      name: 'CakeHouse',
      location: '대전광역시 유성구 덕명동 수서로 1',
    },
    writer: {
      id: 1,
      username: 'userA',
      profile_img: 'https://source.unsplash.com/IhuHLIxS_Tk/1600x900',
    },
    bookmarked: false,
    viewd_num: 10,
  },
  {
    id: 2,
    images: ['https://source.unsplash.com/hrlvr2ZlUNk/1600x900', 'https://source.unsplash.com/cdRUE5bHCGc/1600x900'],
    theme: '가족',
    title: '프랑스 한끼',
    score: 5,
    headcount: 4,
    restaurant: {
      id: 2,
      name: 'ZIP BAP',
      location: '대전광역시 유성구 덕명동 수서로 2',
    },
    writer: {
      id: 2,
      username: 'userB',
      profile_img: 'https://source.unsplash.com/lkMJcGDZLVs/1600x900',
    },
    bookmarked: true,
    viewd_num: 12,
  },
];
export { testCase };
